language: android
jdk: oraclejdk8
branches:
  only:
  - master
  - develop
env:
  global:
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=21.1.2
    - ANDROID_ABI=google_apis/armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL

  sudo: false
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - intel-android-extra-license.+
  cache:
    directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
before_script:
  - ./code-check.sh
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
after_success:
  - ./bintray-upload.sh