name: SecureStorage Github Actions CI

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  assemble:
    name: AssembleDebug SecureStorage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug SecureStorage
        run: bash ./gradlew assembleDebug --stacktrace

  test:
    needs: assemble
    name: Test SecureStorage
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [21, 22, 23, 25, 29]
        target: [default]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Test SecureStorage
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=de.adorsys.android.securestoragetest.SecureStorageLogicTest --stacktrace


  publish:
    on:
      push:
        branches:
          - master
      pull_request:
        branches:
          - master
    needs: [assemble, test]
    name: Publish SecureStorage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish SecureStorage
        run: bash .buildscripts/build-and-deploy-snapshot.sh
