name: Build SecureStorage 2.0

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'legacy/secure-storage-1'

jobs:
  assemble:
    name: AssembleDebug SecureStorage 2.0
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug SecureStorage
        run: |
          bash ./gradlew detekt --stacktrace
          bash ./gradlew assembleDebug --stacktrace